### ISSUE TITLE
Popup/payment issue

### ISSUE THREAD

**Issue by hegeati** [paylike/plugin-opencart-3#11] opened 2020-08-25 09:41 UTC
Dear Developer!

We moved our website to a new opencart 3.0 theme. We set up the paylike module which is worked perfectly before but now after you fill out the details (card number etc) the payment option is not available, only the “save card” as you can see on the attached picture. 

Website: https://palinka.hu/

![C4A39E76-AF89-4C2B-930C-CFA579534A69](https://user-images.githubusercontent.com/70201340/91159034-c9fe7b80-e6c7-11ea-8a20-59d95d09ae39.png)

**Comment by cosminbosutar** [comment] 2020-08-25 12:50
Hello @hegeati,

Thank you for sharing this!

If I understand correctly, the problem your facing is the fact that the payment button doesn't appear after you fill out the payment details in the .

Could you please share the information:
  - Can you please tell us what is the exact opencart version that you are using?
  - Can you please tell us what is the plugin version that you are using?
  - Can you please tell us what php version are you using?
  - Can you please give us more details or a marketplace link about the previous theme you were using?
  - Can you please give us more details or a marketplace link about the new theme you moved too?

@hegeati can you please share the above information with us in order for us to be able to investigate further?

Thank you!
Cosmin

**Comment by hegeati** [comment] 2020-08-25 18:30
*Dear Cosmin,*

   - Can you please tell us what is the exact opencart version that you are
   using?  *3.0.3.6 *
   - Can you please tell us what is the plugin version that you are using?
   *1.0.8*
   - Can you please tell us what php version are you using? *7.3*
   - Can you please give us more details or a marketplace link about the
   previous theme you were using?
   - *https://themeforest.net/item/sellegance-responsive-and-clean-opencart-theme/1285060
   <https://themeforest.net/item/sellegance-responsive-and-clean-opencart-theme/1285060>
 *


   - Can you please give us more details or a marketplace link about the
   new theme you moved too?
   - *https://themeforest.net/item/journal-advanced-opencart-theme/4260361
   <https://themeforest.net/item/journal-advanced-opencart-theme/4260361>  *


genuineq <notifications@github.com> ezt írta (időpont: 2020. aug. 25., K,
14:51):

**Comment by hegeati** [comment] 2020-08-28 04:56
Dear Cosmin,

Is there any news or development about the issue?

genuineq <notifications@github.com> ezt írta (időpont: 2020. aug. 25., K,
14:51):

**Comment by cosminbosutar** [comment] 2020-08-28 11:35
Hello @hegeati 

We have tried to replicate the bug with no success so far.

We tried to replicate the bug on the opencart version you mentioned with the default theme and it happened to also have a copy of the new theme you are using and we tried to replicate the bug with this theme as well but with no success.

Considering the above, we currently suspect that the problem is related to the theme or your specific setup and not with the plugin.

One possible problem could be related with reading the currency and the price when opening the payment popup.

Can you please specify if there are any console messages/errors displayed when opening the payment popup?
Can you please perform a test in which you change the currency? 

Thank you!
Cosmin

**Comment by hegeati** [comment] 2020-08-29 08:23
Thanks for your support!
The popup is working perfectly now, but i did not change anything so i
don't know what was the problem.

Have a nice weekend!

genuineq <notifications@github.com> ezt írta (időpont: 2020. aug. 28., P,
13:35):

**Comment by ionutcalara** [comment] 2021-01-29 10:25
I am closing this, but feel free to reopen.

**Closed by ionutcalara** 2021-01-29 10:25 UTC
